### PR TITLE
chore: Update version to 6.1.13

### PR DESCRIPTION
**Pull request by starhcq**
Update version to 6.1.13
   相关PR:
   * #266
   * #267
   * #268
   * #269
   * #270
   * #271

Log: Update version to 6.1.13

### CODE REVIEW

**Review by pengfeixx — APPROVED** [review]

**Comment by myk1343** [comment]
[是否满足兼容性要求] y
[是否满足commit提交规范] y
[是否满足编码规范] y
[review结论] pass
[fail原因] n/a

**Comment by pengfeixx** [comment]
[是否满足兼容性要求] y
[是否满足commit提交规范] y
[是否满足编码规范] y
[review结论] pass
[fail原因] n/a

**Review by lzwind — APPROVED** [review]

**Pull request merged**
