### PR TITLE
fix: 页面内“级别”显示为“level

### PR DESCRIPTION
**Pull request by Tw1012**
页面内“级别”显示为“level

Log: 页面内“级别”显示为“level
Bug: https://pms.uniontech.com/bug-view-260291.html

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by rb-union** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by starhcq — APPROVED** [review]
/+1

**Pull request merged**
