### PR TITLE
perf: Optimization of kernel/window management log memory usage

### PR DESCRIPTION
**Pull request by starhcq**
Optimization of kernel/window management log memory usage

Log: Optimization of kernel/window management log memory usage
Bug: https://pms.uniontech.com/bug-view-244067.html

### CODE REVIEW

**Review by rb-union — COMMENTED** [review]
有Cppcheck问题

**Review by rb-union — COMMENTED** [review]
有cppcheck问题

**Comment by starhcq** [comment]
> 有cppcheck问题

ut代码中有在使用，为cppcheck误报

**Review by rb-union — COMMENTED** [review]
[是否满足兼容性要求] y
[是否满足commit提交规范] y
[是否满足编码规范] y
[review结论] pass
[fail原因] n/a

**Review by lzwind — APPROVED** [review]

**Pull request merged**
